[frontend]
root@frontend-1@orb ansible_user=root@frontend-1 orb_domain=frontend-1.orb.local
root@frontend-2@orb ansible_user=root@frontend-2 orb_domain=frontend-2.orb.local

[backend]
root@backend-1@orb ansible_user=root@backend-1 orb_domain=backend-1.orb.local
root@backend-2@orb ansible_user=root@backend-2 orb_domain=backend-2.orb.local

[db]
root@db-1@orb ansible_user=root@db-1 orb_domain=db-1.orb.local
root@db-2@orb ansible_user=root@db-2 orb_domain=db-2.orb.local

